spring.data.mongodb.uri=mongodb+srv://mendozapadilla_db_user:juanfe001@eva-u2-spring.brcuerv.mongodb.net/discografica-db?retryWrites=true&w=majority&appName=eva-u2-spring
spring.data.mongodb.database=discografica-db
server.port=8081
